#!/usr/bin/env python3
"""
PR19 Validation — Candidate Page Discovery & Ranking

Compares PR18 (navigator-based, top-3) vs PR19 (candidate-ranker, top-5)
on the full Top-100 US infrastructure professors dataset.

Usage:
    python3.11 tools/pr19_validation.py [--skip-pipeline]

Flags:
    --skip-pipeline   Re-use existing pr19_research_group_graph.json if present.

Reports:
    • Homepage success rate
    • Candidate page coverage (PR19 only)
    • Member discovery rate (professors with ≥1 member)
    • Total members extracted (current + former)
    • Average members per professor
    • Candidate page success rate (PR19 only)
    • Average candidates per professor (PR19 only)
    • Precision/Recall observations (side-by-side PR18 vs PR19)
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

OUTPUT_DIR = Path("data/output")
HOMEPAGE_GRAPH_FILE = OUTPUT_DIR / "homepage_graph.json"
TOP100_JSON = OUTPUT_DIR / "top100_us_professors.json"

# PR18 baseline graphs (generated by pr18_evaluation_runner.py)
PR18_GRAPH_FILE = OUTPUT_DIR / "research_group_graph.json"

# PR19 output graphs
PR19_GRAPH_FILE = OUTPUT_DIR / "pr19_research_group_graph.json"
PR19_REPORT_MD = OUTPUT_DIR / "PR19_VALIDATION_REPORT.md"
PR19_REPORT_JSON = OUTPUT_DIR / "PR19_VALIDATION_REPORT.json"

TARGET_N = 100


# ─────────────────────────────────────────────────────────────────────────────
# Pipeline runner
# ─────────────────────────────────────────────────────────────────────────────

def run_pr19_pipeline(skip: bool = False) -> list[dict]:
    """Run the PR19 pipeline and return serialised graphs."""
    if skip and PR19_GRAPH_FILE.exists():
        existing = json.loads(PR19_GRAPH_FILE.read_text(encoding="utf-8"))
        if len(existing) >= TARGET_N:
            print(f"[PR19] --skip-pipeline: reusing {len(existing)} existing PR19 graphs.")
            return existing

    from homepage_agent.models import HomepageGraph
    from homepage_agent.homepage_resolver import CanonicalHomepageResolver
    from homepage_agent.pipeline import HomepagePipeline
    from homepage_agent.providers.stub import StubNavigatorProvider
    from models.author import Author
    from models.author_profile import AuthorProfile
    from models.professor_profile import ProfessorProfile
    from research_group_agent.pipeline import ResearchGroupPipeline
    from research_group_agent.providers.stub import StubResearchGroupProvider
    from research_group_agent.report import ResearchGroupReport

    print("[PR19] Loading homepage graphs …")
    hp_raw = json.loads(HOMEPAGE_GRAPH_FILE.read_text(encoding="utf-8"))
    homepage_graphs = [HomepageGraph.from_dict(item) for item in hp_raw]
    print(f"[PR19]   {len(homepage_graphs)} homepage graphs loaded.")

    print("[PR19] Resolving canonical homepages …")
    hp_pipeline = HomepagePipeline(provider=StubNavigatorProvider())
    resolver = CanonicalHomepageResolver(homepage_pipeline=hp_pipeline)
    resolved_graphs = resolver.resolve_many(homepage_graphs[:TARGET_N])
    print(f"[PR19]   {len(resolved_graphs)} resolved.")

    professors: list[ProfessorProfile] = []
    for graph in resolved_graphs:
        profile = AuthorProfile(
            author=Author(pid=None, name=graph.professor_name),
            papers=[],
        )
        professor = ProfessorProfile(
            author_profile=profile,
            homepage=graph.homepage_url,
            homepage_graph=graph,
            is_us=True,
        )
        professors.append(professor)

    print(f"[PR19] Running PR19 pipeline on {len(professors)} professors …")
    rg_pipeline = ResearchGroupPipeline(
        provider=StubResearchGroupProvider(),
        top_n=TARGET_N,
    )
    graphs = rg_pipeline.analyze_many(professors)
    print(f"[PR19]   Pipeline complete. {len(graphs)} graphs produced.")

    # Write PR19 graphs
    serialised = [g.to_dict() for g in graphs]
    PR19_GRAPH_FILE.parent.mkdir(parents=True, exist_ok=True)
    PR19_GRAPH_FILE.write_text(
        json.dumps(serialised, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"[PR19] Wrote PR19 graphs to {PR19_GRAPH_FILE}")

    # Also overwrite the canonical graph file and report
    ResearchGroupReport.write(graphs, metrics=rg_pipeline.last_metrics)

    return serialised


# ─────────────────────────────────────────────────────────────────────────────
# Metric helpers
# ─────────────────────────────────────────────────────────────────────────────

def _compute_metrics(graphs: list[dict]) -> dict[str, Any]:
    """Compute comparable metrics from a list of serialised ResearchGroupGraph dicts."""
    total = len(graphs) or 1

    homepage_success = sum(
        1 for g in graphs
        if g.get("fetch_status") not in ("skipped", "not_attempted")
        and g.get("canonical_homepage")
    )

    profs_with_group_page = sum(1 for g in graphs if g.get("group_page"))

    profs_with_members = sum(1 for g in graphs if g.get("member_count", 0) > 0)

    total_current = sum(g.get("current_member_count", g.get("member_count", 0)) for g in graphs)
    total_former = sum(g.get("former_member_count", 0) for g in graphs)
    total_members = total_current + total_former

    member_counts = [g.get("member_count", 0) for g in graphs]
    avg_members = round(sum(member_counts) / total, 2)

    # Multi-page
    total_parsed = sum(len(g.get("parsed_pages", [])) for g in graphs)
    total_successful = sum(len(g.get("successful_pages", [])) for g in graphs)
    avg_parsed = round(total_parsed / total, 2)

    # PR19: candidate pages discovered
    total_candidates = sum(g.get("candidate_pages_discovered", 0) for g in graphs)
    avg_candidates = round(total_candidates / total, 2)

    candidate_success_rate = (
        round(total_successful / total_parsed, 3) if total_parsed > 0 else 0.0
    )

    # Fetch status distribution
    status_dist: dict[str, int] = defaultdict(int)
    for g in graphs:
        status_dist[g.get("fetch_status", "unknown")] += 1

    # Pipeline version
    pipeline_version = graphs[0].get("pipeline_version", "unknown") if graphs else "unknown"
    schema_version = graphs[0].get("schema_version", "unknown") if graphs else "unknown"

    return {
        "pipeline_version": pipeline_version,
        "schema_version": schema_version,
        "total_professors": total,
        "homepage_success_count": homepage_success,
        "homepage_success_rate": round(homepage_success / total, 3),
        "navigation_success_count": profs_with_group_page,
        "navigation_success_rate": round(profs_with_group_page / total, 3),
        "member_discovery_count": profs_with_members,
        "member_discovery_rate": round(profs_with_members / total, 3),
        "total_current_members": total_current,
        "total_former_members": total_former,
        "total_members": total_members,
        "average_members_per_professor": avg_members,
        "total_pages_parsed": total_parsed,
        "total_pages_successful": total_successful,
        "average_pages_parsed": avg_parsed,
        "total_candidates_discovered": total_candidates,
        "average_candidates_per_professor": avg_candidates,
        "candidate_page_success_rate": candidate_success_rate,
        "fetch_status_distribution": dict(status_dist),
    }


def _delta(pr18_val: float | int, pr19_val: float | int) -> str:
    """Format a delta string (+N or -N) for side-by-side comparison."""
    diff = pr19_val - pr18_val
    if isinstance(pr18_val, float) or isinstance(pr19_val, float):
        if diff > 0:
            return f"+{diff:.3f}"
        return f"{diff:.3f}"
    if diff > 0:
        return f"+{diff}"
    return f"{diff}"


# ─────────────────────────────────────────────────────────────────────────────
# Precision / Recall observations
# ─────────────────────────────────────────────────────────────────────────────

def _precision_recall_observations(
    pr18_graphs: list[dict],
    pr19_graphs: list[dict],
) -> list[str]:
    """
    Generate per-professor precision/recall observations by comparing
    member counts between PR18 and PR19.
    """
    observations: list[str] = []
    pr18_by_name = {g["professor_name"]: g for g in pr18_graphs}
    pr19_by_name = {g["professor_name"]: g for g in pr19_graphs}

    gains: list[tuple[str, int, int]] = []
    losses: list[tuple[str, int, int]] = []
    new_discoveries: list[str] = []
    newly_lost: list[str] = []

    for name, p19 in pr19_by_name.items():
        p18 = pr18_by_name.get(name)
        if p18 is None:
            continue
        c18 = p18.get("member_count", 0)
        c19 = p19.get("member_count", 0)

        if c19 > c18:
            gains.append((name, c18, c19))
            if c18 == 0:
                new_discoveries.append(name)
        elif c19 < c18:
            losses.append((name, c18, c19))
            if c19 == 0:
                newly_lost.append(name)

    gains.sort(key=lambda x: x[2] - x[1], reverse=True)
    losses.sort(key=lambda x: x[1] - x[2], reverse=True)

    observations.append(f"New discoveries (PR18=0 → PR19>0): {len(new_discoveries)}")
    for name in new_discoveries[:10]:
        p19 = pr19_by_name[name]
        observations.append(f"  + {name}: {p19.get('member_count', 0)} members")

    if len(new_discoveries) > 10:
        observations.append(f"  ... and {len(new_discoveries) - 10} more")

    observations.append("")
    observations.append(f"Member count gains ({len(gains)} professors improved):")
    for name, before, after in gains[:10]:
        observations.append(f"  {name}: {before} → {after} (+{after - before})")

    if len(gains) > 10:
        observations.append(f"  ... and {len(gains) - 10} more")

    if losses:
        observations.append("")
        observations.append(f"Member count regressions ({len(losses)} professors):")
        for name, before, after in losses[:10]:
            observations.append(f"  {name}: {before} → {after} ({after - before})")
        if newly_lost:
            observations.append(
                f"  Newly lost ({len(newly_lost)}): {', '.join(newly_lost[:5])}"
            )

    return observations


# ─────────────────────────────────────────────────────────────────────────────
# Candidate page type distribution (PR19)
# ─────────────────────────────────────────────────────────────────────────────

def _candidate_type_distribution(pr19_graphs: list[dict]) -> dict[str, int]:
    """Count source_node_types across all parsed pages via group_page entries."""
    from collections import Counter
    dist: Counter[str] = Counter()
    for g in pr19_graphs:
        gp = g.get("group_page")
        if gp:
            dist[gp.get("source_node_type", "unknown")] += 1
    return dict(dist.most_common())


# ─────────────────────────────────────────────────────────────────────────────
# Report rendering
# ─────────────────────────────────────────────────────────────────────────────

def _render_markdown(
    pr18_metrics: dict,
    pr19_metrics: dict,
    observations: list[str],
    type_dist: dict[str, int],
) -> str:
    lines = [
        "# PR19 Validation Report — Candidate Page Discovery & Ranking",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "Compares PR18 (navigator-based, top-3 candidates) vs "
        "PR19 (CandidatePageRanker, top-5 candidates).",
        "",
        "---",
        "",
        "## Side-by-Side Comparison",
        "",
        "| Metric | PR18 | PR19 | Delta |",
        "|--------|------|------|-------|",
    ]

    def row(label: str, k: str, fmt: str = "{}") -> str:
        v18 = pr18_metrics.get(k, 0)
        v19 = pr19_metrics.get(k, 0)
        d = _delta(v18, v19)
        return f"| {label} | {fmt.format(v18)} | {fmt.format(v19)} | {d} |"

    lines.append(row("Total professors", "total_professors", "{}"))
    lines.append(row("Homepage success", "homepage_success_count", "{}"))
    lines.append(row("Homepage success rate", "homepage_success_rate", "{:.1%}"))
    lines.append(row("Navigation success", "navigation_success_count", "{}"))
    lines.append(row("Navigation success rate", "navigation_success_rate", "{:.1%}"))
    lines.append(row("Professors with members", "member_discovery_count", "{}"))
    lines.append(row("Member discovery rate", "member_discovery_rate", "{:.1%}"))
    lines.append(row("Total current members", "total_current_members", "{}"))
    lines.append(row("Total former members", "total_former_members", "{}"))
    lines.append(row("Total members", "total_members", "{}"))
    lines.append(row("Avg members/professor", "average_members_per_professor", "{:.2f}"))
    lines.append(row("Total pages parsed", "total_pages_parsed", "{}"))
    lines.append(row("Total pages successful", "total_pages_successful", "{}"))
    lines.append(row("Avg pages parsed", "average_pages_parsed", "{:.2f}"))

    lines.append("")
    lines.append("### PR19-only Metrics")
    lines.append("")
    lines.append(
        f"- Total candidate pages discovered: **{pr19_metrics.get('total_candidates_discovered', 0)}**"
    )
    lines.append(
        f"- Average candidates per professor: **{pr19_metrics.get('average_candidates_per_professor', 0):.2f}**"
    )
    lines.append(
        f"- Candidate page success rate: **{pr19_metrics.get('candidate_page_success_rate', 0):.1%}**"
    )
    lines.append("")

    if type_dist:
        lines.append("### Candidate Source Node Type Distribution (PR19)")
        lines.append("")
        for node_type, count in type_dist.items():
            lines.append(f"- `{node_type}`: **{count}**")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Precision / Recall Observations")
    lines.append("")
    for obs in observations:
        lines.append(obs)
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## PR18 Fetch Status Distribution")
    lines.append("")
    for status, count in pr18_metrics.get("fetch_status_distribution", {}).items():
        lines.append(f"- `{status}`: **{count}**")
    lines.append("")

    lines.append("## PR19 Fetch Status Distribution")
    lines.append("")
    for status, count in pr19_metrics.get("fetch_status_distribution", {}).items():
        lines.append(f"- `{status}`: **{count}**")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Methodology Notes")
    lines.append("")
    lines.append(
        "- **PR18** used `ResearchGroupNavigator` (top-3 from LAB_PAGE, RG_PAGE, PEOPLE_PAGE)."
    )
    lines.append(
        "- **PR19** uses `CandidatePageGenerator` (ALL HomepageGraph nodes + canonical homepage) "
        "→ `CandidatePageRanker` (top-5 by explainable rule score)."
    )
    lines.append(
        "- Parser, MemberMerger, and downstream extraction logic are **unchanged**."
    )
    lines.append(
        "- Both runs use the same cached HTML (no new network fetches)."
    )
    lines.append("")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    skip = "--skip-pipeline" in sys.argv

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ── Load PR18 baseline ────────────────────────────────────────────────────
    if not PR18_GRAPH_FILE.exists():
        print(
            f"[PR19] ERROR: PR18 baseline not found at {PR18_GRAPH_FILE}. "
            "Run tools/pr18_evaluation_runner.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("[PR19] Loading PR18 baseline …")
    pr18_graphs = json.loads(PR18_GRAPH_FILE.read_text(encoding="utf-8"))
    print(f"[PR19]   {len(pr18_graphs)} PR18 graphs loaded.")

    # ── Run / load PR19 pipeline ──────────────────────────────────────────────
    pr19_graphs = run_pr19_pipeline(skip=skip)

    # ── Compute metrics ───────────────────────────────────────────────────────
    print("[PR19] Computing metrics …")
    pr18_metrics = _compute_metrics(pr18_graphs)
    pr19_metrics = _compute_metrics(pr19_graphs)

    # ── Precision / recall observations ──────────────────────────────────────
    observations = _precision_recall_observations(pr18_graphs, pr19_graphs)

    # ── Candidate type distribution (PR19) ───────────────────────────────────
    type_dist = _candidate_type_distribution(pr19_graphs)

    # ── Assemble full report dict ─────────────────────────────────────────────
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pr18_metrics": pr18_metrics,
        "pr19_metrics": pr19_metrics,
        "candidate_type_distribution": type_dist,
        "precision_recall_observations": observations,
    }

    # ── Write JSON report ─────────────────────────────────────────────────────
    PR19_REPORT_JSON.write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"[PR19] Wrote JSON report to {PR19_REPORT_JSON}")

    # ── Write Markdown report ─────────────────────────────────────────────────
    md = _render_markdown(pr18_metrics, pr19_metrics, observations, type_dist)
    PR19_REPORT_MD.write_text(md, encoding="utf-8")
    print(f"[PR19] Wrote Markdown report to {PR19_REPORT_MD}")

    # ── Print summary ─────────────────────────────────────────────────────────
    print()
    print("=" * 70)
    print("PR19 VALIDATION SUMMARY")
    print("=" * 70)
    print(
        f"{'Metric':<40} {'PR18':>10} {'PR19':>10} {'Delta':>10}"
    )
    print("-" * 70)

    def _pct(v: float) -> str:
        return f"{v:.1%}"

    rows = [
        ("Homepage success rate", "homepage_success_rate", _pct),
        ("Navigation success rate", "navigation_success_rate", _pct),
        ("Member discovery rate", "member_discovery_rate", _pct),
        ("Total members", "total_members", str),
        ("Avg members/professor", "average_members_per_professor", lambda v: f"{v:.2f}"),
        ("Total pages parsed", "total_pages_parsed", str),
        ("Avg pages parsed", "average_pages_parsed", lambda v: f"{v:.2f}"),
    ]

    for label, key, fmt in rows:
        v18 = pr18_metrics.get(key, 0)
        v19 = pr19_metrics.get(key, 0)
        diff = v19 - v18
        if isinstance(v18, float):
            diff_str = f"{diff:+.3f}"
        else:
            diff_str = f"{int(diff):+d}"
        print(f"{label:<40} {fmt(v18):>10} {fmt(v19):>10} {diff_str:>10}")

    print()
    print("PR19-only metrics:")
    print(
        f"  Avg candidates per professor: "
        f"{pr19_metrics.get('average_candidates_per_professor', 0):.2f}"
    )
    print(
        f"  Candidate page success rate:  "
        f"{pr19_metrics.get('candidate_page_success_rate', 0):.1%}"
    )
    print(
        f"  Total candidates discovered:  "
        f"{pr19_metrics.get('total_candidates_discovered', 0)}"
    )
    print()

    print("Precision/Recall (first 5 lines):")
    for line in observations[:5]:
        print(f"  {line}")
    print("=" * 70)


if __name__ == "__main__":
    main()
