#!/usr/bin/env python3
"""
PR20 Validation — Second-hop Candidate Discovery

Compares PR19 (CandidatePageRanker, top-5 first-hop) vs PR20 (+ second-hop
PeoplePageDiscovery on zero-member pages) on the full Top-100 US infrastructure
professors dataset.

Usage:
    python3.11 tools/pr20_validation.py [--skip-pipeline]

Flags:
    --skip-pipeline   Re-use existing pr20_research_group_graph.json if present.

Reports:
    • Homepage success rate
    • Member discovery rate (professors with ≥1 member)
    • Total members extracted (current + former)
    • Average members per professor
    • Second-hop pages discovered / successful (PR20 only)
    • Precision/Recall observations (side-by-side PR19 vs PR20)
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

OUTPUT_DIR = Path("data/output")
HOMEPAGE_GRAPH_FILE = OUTPUT_DIR / "homepage_graph.json"
TOP100_JSON = OUTPUT_DIR / "top100_us_professors.json"

# PR19 baseline (generated by pr19_validation.py or pr18_evaluation_runner.py)
PR19_GRAPH_FILE = OUTPUT_DIR / "pr19_research_group_graph.json"

# PR20 output graphs
PR20_GRAPH_FILE = OUTPUT_DIR / "pr20_research_group_graph.json"
PR20_REPORT_MD = OUTPUT_DIR / "PR20_VALIDATION_REPORT.md"
PR20_REPORT_JSON = OUTPUT_DIR / "PR20_VALIDATION_REPORT.json"

TARGET_N = 100


# ─────────────────────────────────────────────────────────────────────────────
# Pipeline runner
# ─────────────────────────────────────────────────────────────────────────────

def run_pr20_pipeline(skip: bool = False) -> list[dict]:
    """Run the PR20 pipeline and return serialised graphs."""
    if skip and PR20_GRAPH_FILE.exists():
        existing = json.loads(PR20_GRAPH_FILE.read_text(encoding="utf-8"))
        if len(existing) >= TARGET_N:
            print(f"[PR20] --skip-pipeline: reusing {len(existing)} existing PR20 graphs.")
            return existing

    from homepage_agent.models import HomepageGraph
    from homepage_agent.homepage_resolver import CanonicalHomepageResolver
    from homepage_agent.pipeline import HomepagePipeline
    from homepage_agent.providers.stub import StubNavigatorProvider
    from models.author import Author
    from models.author_profile import AuthorProfile
    from models.professor_profile import ProfessorProfile
    from research_group_agent.pipeline import ResearchGroupPipeline
    from research_group_agent.providers.stub import StubResearchGroupProvider
    from research_group_agent.report import ResearchGroupReport

    print("[PR20] Loading homepage graphs …")
    hp_raw = json.loads(HOMEPAGE_GRAPH_FILE.read_text(encoding="utf-8"))
    homepage_graphs = [HomepageGraph.from_dict(item) for item in hp_raw]
    print(f"[PR20]   {len(homepage_graphs)} homepage graphs loaded.")

    print("[PR20] Resolving canonical homepages …")
    hp_pipeline = HomepagePipeline(provider=StubNavigatorProvider())
    resolver = CanonicalHomepageResolver(homepage_pipeline=hp_pipeline)
    resolved_graphs = resolver.resolve_many(homepage_graphs[:TARGET_N])
    print(f"[PR20]   {len(resolved_graphs)} resolved.")

    professors: list[ProfessorProfile] = []
    for graph in resolved_graphs:
        profile = AuthorProfile(
            author=Author(pid=None, name=graph.professor_name),
            papers=[],
        )
        professor = ProfessorProfile(
            author_profile=profile,
            homepage=graph.homepage_url,
            homepage_graph=graph,
            is_us=True,
        )
        professors.append(professor)

    print(f"[PR20] Running PR20 pipeline on {len(professors)} professors …")
    rg_pipeline = ResearchGroupPipeline(
        provider=StubResearchGroupProvider(),
        top_n=TARGET_N,
    )
    graphs = rg_pipeline.analyze_many(professors)
    print(f"[PR20]   Pipeline complete. {len(graphs)} graphs produced.")

    # Summarise second-hop stats
    total_2h_disc = sum(g.second_hop_pages_discovered for g in graphs)
    total_2h_succ = sum(g.second_hop_pages_successful for g in graphs)
    print(
        f"[PR20]   Second-hop pages discovered: {total_2h_disc} | "
        f"successful (≥1 member): {total_2h_succ}"
    )

    # Write PR20 graphs
    serialised = [g.to_dict() for g in graphs]
    PR20_GRAPH_FILE.parent.mkdir(parents=True, exist_ok=True)
    PR20_GRAPH_FILE.write_text(
        json.dumps(serialised, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"[PR20] Wrote PR20 graphs to {PR20_GRAPH_FILE}")

    # Overwrite the canonical graph file and report
    ResearchGroupReport.write(graphs, metrics=rg_pipeline.last_metrics)

    return serialised


# ─────────────────────────────────────────────────────────────────────────────
# Metric helpers
# ─────────────────────────────────────────────────────────────────────────────

def _compute_metrics(graphs: list[dict]) -> dict[str, Any]:
    """Compute comparable metrics from a list of serialised ResearchGroupGraph dicts."""
    total = len(graphs) or 1

    homepage_success = sum(
        1 for g in graphs
        if g.get("fetch_status") not in ("skipped", "not_attempted")
        and g.get("canonical_homepage")
    )

    profs_with_group_page = sum(1 for g in graphs if g.get("group_page"))
    profs_with_members = sum(1 for g in graphs if g.get("member_count", 0) > 0)

    total_current = sum(g.get("current_member_count", g.get("member_count", 0)) for g in graphs)
    total_former = sum(g.get("former_member_count", 0) for g in graphs)
    total_members = total_current + total_former
    avg_members = round(sum(g.get("member_count", 0) for g in graphs) / total, 2)

    total_parsed = sum(len(g.get("parsed_pages", [])) for g in graphs)
    total_successful = sum(len(g.get("successful_pages", [])) for g in graphs)
    avg_parsed = round(total_parsed / total, 2)

    total_candidates = sum(g.get("candidate_pages_discovered", 0) for g in graphs)
    avg_candidates = round(total_candidates / total, 2)

    candidate_success_rate = (
        round(total_successful / total_parsed, 3) if total_parsed > 0 else 0.0
    )

    # PR20: second-hop
    total_2h_disc = sum(g.get("second_hop_pages_discovered", 0) for g in graphs)
    total_2h_succ = sum(g.get("second_hop_pages_successful", 0) for g in graphs)
    profs_with_2h = sum(
        1 for g in graphs if g.get("second_hop_pages_discovered", 0) > 0
    )

    status_dist: dict[str, int] = defaultdict(int)
    for g in graphs:
        status_dist[g.get("fetch_status", "unknown")] += 1

    pipeline_version = graphs[0].get("pipeline_version", "unknown") if graphs else "unknown"
    schema_version = graphs[0].get("schema_version", "unknown") if graphs else "unknown"

    return {
        "pipeline_version": pipeline_version,
        "schema_version": schema_version,
        "total_professors": total,
        "homepage_success_count": homepage_success,
        "homepage_success_rate": round(homepage_success / total, 3),
        "navigation_success_count": profs_with_group_page,
        "navigation_success_rate": round(profs_with_group_page / total, 3),
        "member_discovery_count": profs_with_members,
        "member_discovery_rate": round(profs_with_members / total, 3),
        "total_current_members": total_current,
        "total_former_members": total_former,
        "total_members": total_members,
        "average_members_per_professor": avg_members,
        "total_pages_parsed": total_parsed,
        "total_pages_successful": total_successful,
        "average_pages_parsed": avg_parsed,
        "total_candidates_discovered": total_candidates,
        "average_candidates_per_professor": avg_candidates,
        "candidate_page_success_rate": candidate_success_rate,
        "second_hop_pages_discovered": total_2h_disc,
        "second_hop_pages_successful": total_2h_succ,
        "professors_with_second_hop": profs_with_2h,
        "fetch_status_distribution": dict(status_dist),
    }


def _delta(pr19_val: float | int, pr20_val: float | int) -> str:
    """Format a delta string (+N or -N) for side-by-side comparison."""
    diff = pr20_val - pr19_val
    if isinstance(pr19_val, float) or isinstance(pr20_val, float):
        if diff > 0:
            return f"+{diff:.3f}"
        return f"{diff:.3f}"
    if diff > 0:
        return f"+{diff}"
    return f"{diff}"


# ─────────────────────────────────────────────────────────────────────────────
# Precision / Recall observations
# ─────────────────────────────────────────────────────────────────────────────

def _precision_recall_observations(
    pr19_graphs: list[dict],
    pr20_graphs: list[dict],
) -> list[str]:
    observations: list[str] = []
    pr19_by_name = {g["professor_name"]: g for g in pr19_graphs}
    pr20_by_name = {g["professor_name"]: g for g in pr20_graphs}

    gains: list[tuple[str, int, int]] = []
    losses: list[tuple[str, int, int]] = []
    new_discoveries: list[str] = []
    newly_lost: list[str] = []

    for name, p20 in pr20_by_name.items():
        p19 = pr19_by_name.get(name)
        if p19 is None:
            continue
        c19 = p19.get("member_count", 0)
        c20 = p20.get("member_count", 0)

        if c20 > c19:
            gains.append((name, c19, c20))
            if c19 == 0:
                new_discoveries.append(name)
        elif c20 < c19:
            losses.append((name, c19, c20))
            if c20 == 0:
                newly_lost.append(name)

    gains.sort(key=lambda x: x[2] - x[1], reverse=True)
    losses.sort(key=lambda x: x[1] - x[2], reverse=True)

    observations.append(f"New discoveries (PR19=0 → PR20>0): {len(new_discoveries)}")
    for name in new_discoveries[:10]:
        p20 = pr20_by_name[name]
        observations.append(f"  + {name}: {p20.get('member_count', 0)} members")

    if len(new_discoveries) > 10:
        observations.append(f"  ... and {len(new_discoveries) - 10} more")

    observations.append("")
    observations.append(f"Member count gains ({len(gains)} professors improved):")
    for name, before, after in gains[:10]:
        observations.append(f"  {name}: {before} → {after} (+{after - before})")

    if len(gains) > 10:
        observations.append(f"  ... and {len(gains) - 10} more")

    if losses:
        observations.append("")
        observations.append(f"Member count regressions ({len(losses)} professors):")
        for name, before, after in losses[:10]:
            observations.append(f"  {name}: {before} → {after} ({after - before})")
        if newly_lost:
            observations.append(
                f"  Newly lost ({len(newly_lost)}): {', '.join(newly_lost[:5])}"
            )

    # Second-hop details
    second_hop_pages: list[tuple[str, int, int]] = []
    for name, p20 in pr20_by_name.items():
        disc = p20.get("second_hop_pages_discovered", 0)
        succ = p20.get("second_hop_pages_successful", 0)
        if disc > 0:
            second_hop_pages.append((name, disc, succ))

    second_hop_pages.sort(key=lambda x: x[1], reverse=True)
    if second_hop_pages:
        observations.append("")
        observations.append(
            f"Second-hop pages discovered ({len(second_hop_pages)} professors triggered):"
        )
        for name, disc, succ in second_hop_pages[:10]:
            observations.append(
                f"  {name}: {disc} discovered, {succ} yielded members"
            )
        if len(second_hop_pages) > 10:
            observations.append(f"  ... and {len(second_hop_pages) - 10} more")

    return observations


# ─────────────────────────────────────────────────────────────────────────────
# Report rendering
# ─────────────────────────────────────────────────────────────────────────────

def _render_markdown(
    pr19_metrics: dict,
    pr20_metrics: dict,
    observations: list[str],
) -> str:
    lines = [
        "# PR20 Validation Report — Second-hop Candidate Discovery",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "Compares PR19 (CandidatePageRanker, top-5 first-hop) vs "
        "PR20 (+ PeoplePageDiscovery second-hop on zero-member pages).",
        "",
        "---",
        "",
        "## Side-by-Side Comparison",
        "",
        "| Metric | PR19 | PR20 | Delta |",
        "|--------|------|------|-------|",
    ]

    def row(label: str, k: str, fmt: str = "{}") -> str:
        v19 = pr19_metrics.get(k, 0)
        v20 = pr20_metrics.get(k, 0)
        d = _delta(v19, v20)
        return f"| {label} | {fmt.format(v19)} | {fmt.format(v20)} | {d} |"

    lines.append(row("Total professors", "total_professors"))
    lines.append(row("Homepage success", "homepage_success_count"))
    lines.append(row("Homepage success rate", "homepage_success_rate", "{:.1%}"))
    lines.append(row("Navigation success", "navigation_success_count"))
    lines.append(row("Navigation success rate", "navigation_success_rate", "{:.1%}"))
    lines.append(row("Professors with members", "member_discovery_count"))
    lines.append(row("Member discovery rate", "member_discovery_rate", "{:.1%}"))
    lines.append(row("Total current members", "total_current_members"))
    lines.append(row("Total former members", "total_former_members"))
    lines.append(row("Total members", "total_members"))
    lines.append(row("Avg members/professor", "average_members_per_professor", "{:.2f}"))
    lines.append(row("Total pages parsed", "total_pages_parsed"))
    lines.append(row("Total pages successful", "total_pages_successful"))
    lines.append(row("Avg pages parsed", "average_pages_parsed", "{:.2f}"))

    lines.append("")
    lines.append("### PR20-only Metrics")
    lines.append("")
    lines.append(
        f"- Second-hop pages discovered: **{pr20_metrics.get('second_hop_pages_discovered', 0)}**"
    )
    lines.append(
        f"- Second-hop pages successful (≥1 member): **{pr20_metrics.get('second_hop_pages_successful', 0)}**"
    )
    lines.append(
        f"- Professors that triggered second-hop: **{pr20_metrics.get('professors_with_second_hop', 0)}**"
    )
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Precision / Recall Observations")
    lines.append("")
    for obs in observations:
        lines.append(obs)
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## PR19 Fetch Status Distribution")
    lines.append("")
    for status, count in pr19_metrics.get("fetch_status_distribution", {}).items():
        lines.append(f"- `{status}`: **{count}**")
    lines.append("")

    lines.append("## PR20 Fetch Status Distribution")
    lines.append("")
    for status, count in pr20_metrics.get("fetch_status_distribution", {}).items():
        lines.append(f"- `{status}`: **{count}**")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Methodology Notes")
    lines.append("")
    lines.append(
        "- **PR19** uses `CandidatePageGenerator` (ALL HomepageGraph nodes + canonical homepage) "
        "→ `CandidatePageRanker` (top-5 by explainable rule score)."
    )
    lines.append(
        "- **PR20** adds `PeoplePageDiscovery`: when a first-hop page passes validation but "
        "yields zero members, its navigation links are inspected for people/team/member/student "
        "sub-pages, which are fetched once (single hop, no recursion)."
    )
    lines.append(
        "- Parser, validator, MemberMerger, and ranking logic are **unchanged**."
    )
    lines.append(
        "- Both runs use the same cached HTML (no new network fetches beyond second-hop URLs)."
    )
    lines.append("")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    skip = "--skip-pipeline" in sys.argv

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ── Load PR19 baseline ────────────────────────────────────────────────────
    if not PR19_GRAPH_FILE.exists():
        print(
            f"[PR20] ERROR: PR19 baseline not found at {PR19_GRAPH_FILE}. "
            "Run tools/pr19_validation.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    print("[PR20] Loading PR19 baseline …")
    pr19_graphs = json.loads(PR19_GRAPH_FILE.read_text(encoding="utf-8"))
    print(f"[PR20]   {len(pr19_graphs)} PR19 graphs loaded.")

    # ── Run / load PR20 pipeline ──────────────────────────────────────────────
    pr20_graphs = run_pr20_pipeline(skip=skip)

    # ── Compute metrics ───────────────────────────────────────────────────────
    print("[PR20] Computing metrics …")
    pr19_metrics = _compute_metrics(pr19_graphs)
    pr20_metrics = _compute_metrics(pr20_graphs)

    # ── Precision / recall observations ──────────────────────────────────────
    observations = _precision_recall_observations(pr19_graphs, pr20_graphs)

    # ── Assemble full report dict ─────────────────────────────────────────────
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pr19_metrics": pr19_metrics,
        "pr20_metrics": pr20_metrics,
        "precision_recall_observations": observations,
    }

    # ── Write JSON report ─────────────────────────────────────────────────────
    PR20_REPORT_JSON.write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"[PR20] Wrote JSON report to {PR20_REPORT_JSON}")

    # ── Write Markdown report ─────────────────────────────────────────────────
    md = _render_markdown(pr19_metrics, pr20_metrics, observations)
    PR20_REPORT_MD.write_text(md, encoding="utf-8")
    print(f"[PR20] Wrote Markdown report to {PR20_REPORT_MD}")

    # ── Print summary ─────────────────────────────────────────────────────────
    print()
    print("=" * 70)
    print("PR20 VALIDATION SUMMARY")
    print("=" * 70)
    print(f"{'Metric':<40} {'PR19':>10} {'PR20':>10} {'Delta':>10}")
    print("-" * 70)

    def _pct(v: float) -> str:
        return f"{v:.1%}"

    rows = [
        ("Homepage success rate",    "homepage_success_rate",    _pct),
        ("Navigation success rate",  "navigation_success_rate",  _pct),
        ("Member discovery rate",    "member_discovery_rate",    _pct),
        ("Total members",            "total_members",            str),
        ("Avg members/professor",    "average_members_per_professor", lambda v: f"{v:.2f}"),
        ("Total pages parsed",       "total_pages_parsed",       str),
        ("Avg pages parsed",         "average_pages_parsed",     lambda v: f"{v:.2f}"),
    ]

    for label, key, fmt in rows:
        v19 = pr19_metrics.get(key, 0)
        v20 = pr20_metrics.get(key, 0)
        diff = v20 - v19
        diff_str = f"{diff:+.3f}" if isinstance(v19, float) else f"{int(diff):+d}"
        print(f"{label:<40} {fmt(v19):>10} {fmt(v20):>10} {diff_str:>10}")

    print()
    print("PR20-only metrics:")
    print(
        f"  Second-hop pages discovered:   "
        f"{pr20_metrics.get('second_hop_pages_discovered', 0)}"
    )
    print(
        f"  Second-hop pages successful:   "
        f"{pr20_metrics.get('second_hop_pages_successful', 0)}"
    )
    print(
        f"  Professors with second-hop:    "
        f"{pr20_metrics.get('professors_with_second_hop', 0)}"
    )
    print()

    print("Precision/Recall (first 5 lines):")
    for line in observations[:5]:
        print(f"  {line}")
    print("=" * 70)


if __name__ == "__main__":
    main()
