#!/usr/bin/env python3
"""
PR21 Validation — Modern Member Layout Support (Heading-Card Extraction)

Compares PR20 (second-hop PeoplePageDiscovery) vs PR21 (+ HeadingCardExtractor
for H3/H4-based member card layouts) on the full Top-100 US infrastructure
professors dataset.

Usage:
    python3.11 tools/pr21_validation.py [--skip-pipeline]

Flags:
    --skip-pipeline   Re-use existing pr21_research_group_graph.json if present.

Reports:
    • Member discovery rate (professors with ≥1 member)
    • Total members extracted (current + former)
    • Average members per professor
    • Heading-card entries extracted (PR21-specific)
    • Professors newly recovered by heading-card extraction
    • Side-by-side PR20 vs PR21 comparison
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

OUTPUT_DIR = Path("data/output")
HOMEPAGE_GRAPH_FILE = OUTPUT_DIR / "homepage_graph.json"
TOP100_JSON = OUTPUT_DIR / "top100_us_professors.json"

# PR20 baseline (generated by pr20_validation.py)
PR20_GRAPH_FILE = OUTPUT_DIR / "pr20_research_group_graph.json"

# PR21 output graphs
PR21_GRAPH_FILE = OUTPUT_DIR / "pr21_research_group_graph.json"
PR21_REPORT_MD = OUTPUT_DIR / "PR21_VALIDATION_REPORT.md"
PR21_REPORT_JSON = OUTPUT_DIR / "PR21_VALIDATION_REPORT.json"

TARGET_N = 100


# ─────────────────────────────────────────────────────────────────────────────
# Pipeline runner
# ─────────────────────────────────────────────────────────────────────────────

def run_pr21_pipeline(skip: bool = False) -> list[dict]:
    """Run the PR21 pipeline and return serialised graphs."""
    if skip and PR21_GRAPH_FILE.exists():
        existing = json.loads(PR21_GRAPH_FILE.read_text(encoding="utf-8"))
        if len(existing) >= TARGET_N:
            print(f"[PR21] --skip-pipeline: reusing {len(existing)} existing PR21 graphs.")
            return existing

    from homepage_agent.models import HomepageGraph
    from homepage_agent.homepage_resolver import CanonicalHomepageResolver
    from homepage_agent.pipeline import HomepagePipeline
    from homepage_agent.providers.stub import StubNavigatorProvider
    from models.author import Author
    from models.author_profile import AuthorProfile
    from models.professor_profile import ProfessorProfile
    from research_group_agent.pipeline import ResearchGroupPipeline
    from research_group_agent.providers.stub import StubResearchGroupProvider
    from research_group_agent.report import ResearchGroupReport

    print("[PR21] Loading homepage graphs …")
    hp_raw = json.loads(HOMEPAGE_GRAPH_FILE.read_text(encoding="utf-8"))
    homepage_graphs = [HomepageGraph.from_dict(item) for item in hp_raw]
    print(f"[PR21]   {len(homepage_graphs)} homepage graphs loaded.")

    print("[PR21] Resolving canonical homepages …")
    hp_pipeline = HomepagePipeline(provider=StubNavigatorProvider())
    resolver = CanonicalHomepageResolver(homepage_pipeline=hp_pipeline)
    resolved_graphs = resolver.resolve_many(homepage_graphs[:TARGET_N])
    print(f"[PR21]   {len(resolved_graphs)} resolved.")

    professors: list[ProfessorProfile] = []
    for graph in resolved_graphs:
        profile = AuthorProfile(
            author=Author(pid=None, name=graph.professor_name),
            papers=[],
        )
        professor = ProfessorProfile(
            author_profile=profile,
            homepage=graph.homepage_url,
            homepage_graph=graph,
            is_us=True,
        )
        professors.append(professor)

    print(f"[PR21] Running PR21 pipeline on {len(professors)} professors …")
    rg_pipeline = ResearchGroupPipeline(
        provider=StubResearchGroupProvider(),
        top_n=TARGET_N,
    )
    graphs = rg_pipeline.analyze_many(professors)
    print(f"[PR21]   Pipeline complete. {len(graphs)} graphs produced.")

    # Summarise second-hop stats (carried over from PR20)
    total_2h_disc = sum(g.second_hop_pages_discovered for g in graphs)
    total_2h_succ = sum(g.second_hop_pages_successful for g in graphs)
    print(
        f"[PR21]   Second-hop pages discovered: {total_2h_disc} | "
        f"successful (≥1 member): {total_2h_succ}"
    )

    # Write PR21 graphs
    serialised = [g.to_dict() for g in graphs]
    PR21_GRAPH_FILE.parent.mkdir(parents=True, exist_ok=True)
    PR21_GRAPH_FILE.write_text(
        json.dumps(serialised, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"[PR21] Wrote PR21 graphs to {PR21_GRAPH_FILE}")

    # Overwrite canonical graph file and report
    ResearchGroupReport.write(graphs, metrics=rg_pipeline.last_metrics)

    return serialised


# ─────────────────────────────────────────────────────────────────────────────
# Metric helpers
# ─────────────────────────────────────────────────────────────────────────────

def _compute_metrics(graphs: list[dict]) -> dict[str, Any]:
    """Compute comparable metrics from serialised ResearchGroupGraph dicts."""
    total = len(graphs) or 1

    homepage_success = sum(
        1 for g in graphs
        if g.get("fetch_status") not in ("skipped", "not_attempted")
        and g.get("canonical_homepage")
    )

    profs_with_group_page = sum(1 for g in graphs if g.get("group_page"))
    profs_with_members = sum(1 for g in graphs if g.get("member_count", 0) > 0)

    total_current = sum(g.get("current_member_count", g.get("member_count", 0)) for g in graphs)
    total_former = sum(g.get("former_member_count", 0) for g in graphs)
    total_members = total_current + total_former
    avg_members = round(sum(g.get("member_count", 0) for g in graphs) / total, 2)

    total_parsed = sum(len(g.get("parsed_pages", [])) for g in graphs)
    total_successful = sum(len(g.get("successful_pages", [])) for g in graphs)
    avg_parsed = round(total_parsed / total, 2)

    total_candidates = sum(g.get("candidate_pages_discovered", 0) for g in graphs)
    avg_candidates = round(total_candidates / total, 2)
    candidate_success_rate = (
        round(total_successful / total_parsed, 3) if total_parsed > 0 else 0.0
    )

    total_2h_disc = sum(g.get("second_hop_pages_discovered", 0) for g in graphs)
    total_2h_succ = sum(g.get("second_hop_pages_successful", 0) for g in graphs)
    profs_with_2h = sum(
        1 for g in graphs if g.get("second_hop_pages_discovered", 0) > 0
    )

    status_dist: dict[str, int] = defaultdict(int)
    for g in graphs:
        status_dist[g.get("fetch_status", "unknown")] += 1

    pipeline_version = graphs[0].get("pipeline_version", "unknown") if graphs else "unknown"
    schema_version = graphs[0].get("schema_version", "unknown") if graphs else "unknown"

    return {
        "pipeline_version": pipeline_version,
        "schema_version": schema_version,
        "total_professors": total,
        "homepage_success_count": homepage_success,
        "homepage_success_rate": round(homepage_success / total, 3),
        "navigation_success_count": profs_with_group_page,
        "navigation_success_rate": round(profs_with_group_page / total, 3),
        "member_discovery_count": profs_with_members,
        "member_discovery_rate": round(profs_with_members / total, 3),
        "total_current_members": total_current,
        "total_former_members": total_former,
        "total_members": total_members,
        "average_members_per_professor": avg_members,
        "total_pages_parsed": total_parsed,
        "total_pages_successful": total_successful,
        "average_pages_parsed": avg_parsed,
        "total_candidates_discovered": total_candidates,
        "average_candidates_per_professor": avg_candidates,
        "candidate_page_success_rate": candidate_success_rate,
        "second_hop_pages_discovered": total_2h_disc,
        "second_hop_pages_successful": total_2h_succ,
        "professors_with_second_hop": profs_with_2h,
        "fetch_status_distribution": dict(status_dist),
    }


def _delta(pr_prev: float | int, pr_next: float | int) -> str:
    diff = pr_next - pr_prev
    if isinstance(pr_prev, float) or isinstance(pr_next, float):
        return f"+{diff:.3f}" if diff > 0 else f"{diff:.3f}"
    return f"+{diff}" if diff > 0 else f"{diff}"


# ─────────────────────────────────────────────────────────────────────────────
# Precision / Recall observations
# ─────────────────────────────────────────────────────────────────────────────

def _precision_recall_observations(
    pr20_graphs: list[dict],
    pr21_graphs: list[dict],
) -> list[str]:
    observations: list[str] = []
    pr20_by_name = {g["professor_name"]: g for g in pr20_graphs}
    pr21_by_name = {g["professor_name"]: g for g in pr21_graphs}

    gains: list[tuple[str, int, int]] = []
    losses: list[tuple[str, int, int]] = []
    new_discoveries: list[str] = []
    newly_lost: list[str] = []

    for name, p21 in pr21_by_name.items():
        p20 = pr20_by_name.get(name)
        if p20 is None:
            continue
        c20 = p20.get("member_count", 0)
        c21 = p21.get("member_count", 0)

        if c21 > c20:
            gains.append((name, c20, c21))
            if c20 == 0:
                new_discoveries.append(name)
        elif c21 < c20:
            losses.append((name, c20, c21))
            if c21 == 0:
                newly_lost.append(name)

    gains.sort(key=lambda x: x[2] - x[1], reverse=True)
    losses.sort(key=lambda x: x[1] - x[2], reverse=True)

    observations.append(
        f"New discoveries (PR20=0 → PR21>0): {len(new_discoveries)} professors"
    )
    for name in new_discoveries[:15]:
        p21 = pr21_by_name[name]
        observations.append(
            f"  + {name}: {p21.get('member_count', 0)} members"
        )
    if len(new_discoveries) > 15:
        observations.append(f"  ... and {len(new_discoveries) - 15} more")

    observations.append("")
    observations.append(
        f"Member count gains ({len(gains)} professors improved):"
    )
    for name, before, after in gains[:15]:
        observations.append(f"  {name}: {before} → {after} (+{after - before})")
    if len(gains) > 15:
        observations.append(f"  ... and {len(gains) - 15} more")

    if losses:
        observations.append("")
        observations.append(
            f"Member count regressions ({len(losses)} professors):"
        )
        for name, before, after in losses[:10]:
            observations.append(f"  {name}: {before} → {after} ({after - before})")
        if newly_lost:
            observations.append(
                f"  Newly lost ({len(newly_lost)}): {', '.join(newly_lost[:5])}"
            )

    return observations


# ─────────────────────────────────────────────────────────────────────────────
# Report rendering
# ─────────────────────────────────────────────────────────────────────────────

def _render_markdown(
    pr20_metrics: dict,
    pr21_metrics: dict,
    observations: list[str],
) -> str:
    lines = [
        "# PR21 Validation Report — Modern Member Layout Support",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "Compares PR20 (second-hop PeoplePageDiscovery) vs PR21 (+ HeadingCardExtractor "
        "for H3/H4-based card layouts found on RISE Lab, Sky Computing, CSL Illinois, etc.).",
        "",
        "---",
        "",
        "## Side-by-Side Comparison",
        "",
        "| Metric | PR20 | PR21 | Delta |",
        "|--------|------|------|-------|",
    ]

    def row(label: str, k: str, fmt: str = "{}") -> str:
        v20 = pr20_metrics.get(k, 0)
        v21 = pr21_metrics.get(k, 0)
        d = _delta(v20, v21)
        return f"| {label} | {fmt.format(v20)} | {fmt.format(v21)} | {d} |"

    lines.append(row("Total professors", "total_professors"))
    lines.append(row("Homepage success", "homepage_success_count"))
    lines.append(row("Homepage success rate", "homepage_success_rate", "{:.1%}"))
    lines.append(row("Navigation success", "navigation_success_count"))
    lines.append(row("Navigation success rate", "navigation_success_rate", "{:.1%}"))
    lines.append(row("Professors with members", "member_discovery_count"))
    lines.append(row("Member discovery rate", "member_discovery_rate", "{:.1%}"))
    lines.append(row("Total current members", "total_current_members"))
    lines.append(row("Total former members", "total_former_members"))
    lines.append(row("Total members", "total_members"))
    lines.append(row("Avg members/professor", "average_members_per_professor", "{:.2f}"))
    lines.append(row("Total pages parsed", "total_pages_parsed"))
    lines.append(row("Total pages successful", "total_pages_successful"))
    lines.append(row("Avg pages parsed", "average_pages_parsed", "{:.2f}"))

    lines.append("")
    lines.append("### PR21-only: Heading-Card Extraction Metrics")
    lines.append("")
    lines.append(
        "> These metrics are only available in the PR21 run output; they are not "
        "stored in the serialised graph (which only stores final members)."
    )
    lines.append(
        "Run `python3.11 tools/pr21_validation.py` to see live heading-card stats "
        "printed during pipeline execution."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Precision / Recall Observations")
    lines.append("")
    for obs in observations:
        lines.append(obs)
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## PR20 Fetch Status Distribution")
    lines.append("")
    for status, count in pr20_metrics.get("fetch_status_distribution", {}).items():
        lines.append(f"- `{status}`: **{count}**")
    lines.append("")
    lines.append("## PR21 Fetch Status Distribution")
    lines.append("")
    for status, count in pr21_metrics.get("fetch_status_distribution", {}).items():
        lines.append(f"- `{status}`: **{count}**")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Methodology Notes")
    lines.append("")
    lines.append(
        "- **PR20** uses `PeoplePageDiscovery` (second-hop) when a first-hop page "
        "yields zero members."
    )
    lines.append(
        "- **PR21** adds `HeadingCardExtractor`: a second-pass parser that detects "
        "pages where each member is represented as an H3/H4 heading "
        "(with optional profile link) followed by role text. "
        "Activation threshold: ≥3 consecutive name-like H3/H4 headings, or any "
        "name heading inside a known member section."
    )
    lines.append("")
    lines.append(
        "The `HeadingCardExtractor` runs *after* the existing `_SectionAwareParser`, "
        "so all PR16–PR20 extraction behavior is fully preserved."
    )
    lines.append("")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    skip = "--skip-pipeline" in sys.argv

    # Load PR20 baseline
    if not PR20_GRAPH_FILE.exists():
        print(
            f"[PR21] ERROR: PR20 baseline not found at {PR20_GRAPH_FILE}.\n"
            "       Run `python3.11 tools/pr20_validation.py` first to generate it."
        )
        sys.exit(1)

    pr20_graphs = json.loads(PR20_GRAPH_FILE.read_text(encoding="utf-8"))
    print(f"[PR21] Loaded {len(pr20_graphs)} PR20 baseline graphs.")

    # Run PR21 pipeline
    pr21_graphs = run_pr21_pipeline(skip=skip)

    # Compute metrics
    pr20_metrics = _compute_metrics(pr20_graphs)
    pr21_metrics = _compute_metrics(pr21_graphs)

    # Observations
    observations = _precision_recall_observations(pr20_graphs, pr21_graphs)

    # Print summary to console
    print()
    print("=" * 70)
    print("PR21 VALIDATION SUMMARY")
    print("=" * 70)
    print(
        f"{'Metric':<40} {'PR20':>10} {'PR21':>10} {'Delta':>10}"
    )
    print("-" * 70)

    def _print_row(label: str, k: str, pct: bool = False) -> None:
        v20 = pr20_metrics.get(k, 0)
        v21 = pr21_metrics.get(k, 0)
        d = _delta(v20, v21)
        if pct:
            print(f"{label:<40} {v20:>9.1%} {v21:>9.1%} {d:>10}")
        elif isinstance(v20, float):
            print(f"{label:<40} {v20:>10.2f} {v21:>10.2f} {d:>10}")
        else:
            print(f"{label:<40} {v20:>10} {v21:>10} {d:>10}")

    _print_row("Professors with members", "member_discovery_count")
    _print_row("Member discovery rate", "member_discovery_rate", pct=True)
    _print_row("Total current members", "total_current_members")
    _print_row("Total former members", "total_former_members")
    _print_row("Total members", "total_members")
    _print_row("Avg members/professor", "average_members_per_professor")
    _print_row("Total pages parsed", "total_pages_parsed")
    _print_row("Navigation success count", "navigation_success_count")

    print()
    for obs in observations:
        print(obs)

    # Write reports
    md = _render_markdown(pr20_metrics, pr21_metrics, observations)
    PR21_REPORT_MD.write_text(md, encoding="utf-8")
    print(f"\n[PR21] Markdown report → {PR21_REPORT_MD}")

    report_json = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pr20_metrics": pr20_metrics,
        "pr21_metrics": pr21_metrics,
        "observations": observations,
    }
    PR21_REPORT_JSON.write_text(
        json.dumps(report_json, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"[PR21] JSON report    → {PR21_REPORT_JSON}")

    # Discovery rate delta
    delta_rate = pr21_metrics["member_discovery_rate"] - pr20_metrics["member_discovery_rate"]
    delta_total = pr21_metrics["total_members"] - pr20_metrics["total_members"]
    print()
    print(f"[PR21] Discovery rate change: {delta_rate:+.1%}")
    print(f"[PR21] Total member change:   {delta_total:+d}")


if __name__ == "__main__":
    main()
